/**
 * Example Plasmo popup component
 * The @layout decorator tells plasmo-layout which layout template to use
 */

// @layout('popup')

export default function Popup() {
  return (
    <div className="popup-content">
      <h1>Welcome to My Extension</h1>
      <p>This popup uses a custom layout generated by plasmo-layout.</p>
      <button onClick={() => alert('Hello!')}>Click Me</button>
    </div>
  );
}
